### ISSUE TITLE
where is the repo of flask-htmlbuilder project?

### ISSUE THREAD

**Issue by zakfriend** [quokkaproject/quokka#176]
When I want to install the dependencies with requirements I have this error HTTP error 404 while getting https://github.com/majorz/flask-htmlbuilder/tarball/master

**Comment by ellisonleao** [comment]
hey @zakfriend  thanks for the feedback. I just fixed it on requirements.

**Comment by zakfriend** [comment]
Thanks @ellisonleao , but there's still the same problem "Could not find any downloads that satisfy the requirement Flask-HTMLBuilder" the project flask-htmlbuilder seems to have disappeared

**Comment by rochacbruno** [comment]
Looks like https://github.com/majorz @majorz deleted all repositories

**Comment by rochacbruno** [comment]
Also deleted from PyPI https://pypi.python.org/pypi/Flask-HTMLBuilder

**Comment by rochacbruno** [comment]
Found this, but outdated https://github.com/handloomweaver/flask-htmlbuilder

**Comment by rochacbruno** [comment]
I found the code, will fix it using another repo

**Comment by zakfriend** [comment]
Ok great thanks @rochacbruno

**Comment by ellisonleao** [comment]
That's strange, i was able to install from the Pypi repo with no issues. Can't we use it?

**Comment by rochacbruno** [comment]
Fixed @zakfriend @ellisonleao I recovered from my local installation and published here https://github.com/quokkaproject/flask-htmlbuilder fixed!

**Comment by zakfriend** [comment]
Cool! I can try quokka now!

**Comment by ellisonleao** [comment]
ok!
